// File generated from our OpenAPI spec
namespace Stripe
{
    using Newtonsoft.Json;
    using Stripe.Infrastructure;
    using STJS = System.Text.Json.Serialization;

    [STJS.JsonConverter(typeof(STJStripeEntityConverter))]
    public class PaymentRecordPaymentMethodDetailsPix : StripeEntity<PaymentRecordPaymentMethodDetailsPix>
    {
        /// <summary>
        /// Unique transaction id generated by BCB.
        /// </summary>
        [JsonProperty("bank_transaction_id")]
        [STJS.JsonPropertyName("bank_transaction_id")]
        public string BankTransactionId { get; set; }
    }
}
