// File generated from our OpenAPI spec
namespace Stripe
{
    using Newtonsoft.Json;
    using Stripe.Infrastructure;
    using STJS = System.Text.Json.Serialization;

    [STJS.JsonConverter(typeof(STJStripeEntityConverter))]
    public class PaymentAttemptRecordPaymentMethodDetailsPaypal : StripeEntity<PaymentAttemptRecordPaymentMethodDetailsPaypal>
    {
        /// <summary>
        /// Two-letter ISO code representing the buyer's country. Values are provided by PayPal
        /// directly (if supported) at the time of authorization or settlement. They cannot be set
        /// or mutated.
        /// </summary>
        [JsonProperty("country")]
        [STJS.JsonPropertyName("country")]
        public string Country { get; set; }

        /// <summary>
        /// Owner's email. Values are provided by PayPal directly (if supported) at the time of
        /// authorization or settlement. They cannot be set or mutated.
        /// </summary>
        [JsonProperty("payer_email")]
        [STJS.JsonPropertyName("payer_email")]
        public string PayerEmail { get; set; }

        /// <summary>
        /// PayPal account PayerID. This identifier uniquely identifies the PayPal customer.
        /// </summary>
        [JsonProperty("payer_id")]
        [STJS.JsonPropertyName("payer_id")]
        public string PayerId { get; set; }

        /// <summary>
        /// Owner's full name. Values provided by PayPal directly (if supported) at the time of
        /// authorization or settlement. They cannot be set or mutated.
        /// </summary>
        [JsonProperty("payer_name")]
        [STJS.JsonPropertyName("payer_name")]
        public string PayerName { get; set; }

        /// <summary>
        /// The level of protection offered as defined by PayPal Seller Protection for Merchants,
        /// for this transaction.
        /// </summary>
        [JsonProperty("seller_protection")]
        [STJS.JsonPropertyName("seller_protection")]
        public PaymentAttemptRecordPaymentMethodDetailsPaypalSellerProtection SellerProtection { get; set; }

        /// <summary>
        /// A unique ID generated by PayPal for this transaction.
        /// </summary>
        [JsonProperty("transaction_id")]
        [STJS.JsonPropertyName("transaction_id")]
        public string TransactionId { get; set; }
    }
}
