// File generated from our OpenAPI spec
namespace Stripe
{
    using Newtonsoft.Json;
#if NET6_0_OR_GREATER
    using STJS = System.Text.Json.Serialization;
#endif

    public class PaymentAttemptRecordPaymentMethodDetailsPaypal : StripeEntity<PaymentAttemptRecordPaymentMethodDetailsPaypal>
    {
        /// <summary>
        /// Two-letter ISO code representing the buyer's country. Values are provided by PayPal
        /// directly (if supported) at the time of authorization or settlement. They cannot be set
        /// or mutated.
        /// </summary>
        [JsonProperty("country")]
#if NET6_0_OR_GREATER
        [STJS.JsonPropertyName("country")]
#endif
        public string Country { get; set; }

        /// <summary>
        /// Owner's email. Values are provided by PayPal directly (if supported) at the time of
        /// authorization or settlement. They cannot be set or mutated.
        /// </summary>
        [JsonProperty("payer_email")]
#if NET6_0_OR_GREATER
        [STJS.JsonPropertyName("payer_email")]
#endif
        public string PayerEmail { get; set; }

        /// <summary>
        /// PayPal account PayerID. This identifier uniquely identifies the PayPal customer.
        /// </summary>
        [JsonProperty("payer_id")]
#if NET6_0_OR_GREATER
        [STJS.JsonPropertyName("payer_id")]
#endif
        public string PayerId { get; set; }

        /// <summary>
        /// Owner's full name. Values provided by PayPal directly (if supported) at the time of
        /// authorization or settlement. They cannot be set or mutated.
        /// </summary>
        [JsonProperty("payer_name")]
#if NET6_0_OR_GREATER
        [STJS.JsonPropertyName("payer_name")]
#endif
        public string PayerName { get; set; }

        /// <summary>
        /// The level of protection offered as defined by PayPal Seller Protection for Merchants,
        /// for this transaction.
        /// </summary>
        [JsonProperty("seller_protection")]
#if NET6_0_OR_GREATER
        [STJS.JsonPropertyName("seller_protection")]
#endif
        public PaymentAttemptRecordPaymentMethodDetailsPaypalSellerProtection SellerProtection { get; set; }

        /// <summary>
        /// A unique ID generated by PayPal for this transaction.
        /// </summary>
        [JsonProperty("transaction_id")]
#if NET6_0_OR_GREATER
        [STJS.JsonPropertyName("transaction_id")]
#endif
        public string TransactionId { get; set; }
    }
}
