// File generated from our OpenAPI spec
namespace Stripe
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Stripe.Infrastructure;
    using STJS = System.Text.Json.Serialization;


    [STJS.JsonConverter(typeof(STJStripeEntityConverter))]
    public class SetupIntentPaymentMethodOptionsPaypal : StripeEntity<SetupIntentPaymentMethodOptionsPaypal>
    {
        /// <summary>
        /// The PayPal Billing Agreement ID (BAID). This is an ID generated by PayPal which
        /// represents the mandate between the merchant and the customer.
        /// </summary>
        [JsonProperty("billing_agreement_id")]
        [STJS.JsonPropertyName("billing_agreement_id")]
        public string BillingAgreementId { get; set; }

        /// <summary>
        /// Three-letter <a href="https://www.iso.org/iso-4217-currency-codes.html">ISO currency
        /// code</a>, in lowercase. Must be a <a href="https://stripe.com/docs/currencies">supported
        /// currency</a>.
        /// </summary>
        [JsonProperty("currency")]
        [STJS.JsonPropertyName("currency")]
        public string Currency { get; set; }

        /// <summary>
        /// The Stripe connected account IDs of the sellers on the platform for this transaction
        /// (optional). Only allowed when <a
        /// href="https://stripe.com/docs/connect/separate-charges-and-transfers">separate charges
        /// and transfers</a> are used.
        /// </summary>
        [JsonProperty("subsellers")]
        [STJS.JsonPropertyName("subsellers")]
        public List<string> Subsellers { get; set; }
    }
}
