// File generated from our OpenAPI spec
namespace Stripe
{
    using Newtonsoft.Json;

    public class QuoteInvoiceSettings : StripeEntity<QuoteInvoiceSettings>
    {
        /// <summary>
        /// Number of days within which a customer must pay invoices generated by this quote. This
        /// value will be <c>null</c> for quotes where
        /// <c>collection_method=charge_automatically</c>.
        /// </summary>
        [JsonProperty("days_until_due")]
        public long? DaysUntilDue { get; set; }

        /// <summary>
        /// The connected account that issues the invoice. The invoice is presented with the
        /// branding and support information of the specified account.
        /// </summary>
        [JsonProperty("issuer")]
        public QuoteInvoiceSettingsIssuer Issuer { get; set; }
    }
}
