// File generated from our OpenAPI spec
namespace Stripe
{
    using Newtonsoft.Json;

    public class SubscriptionAutomaticTaxOptions : INestedOptions
    {
        /// <summary>
        /// Enabled automatic tax calculation which will automatically compute tax rates on all
        /// invoices generated by the subscription.
        /// </summary>
        [JsonProperty("enabled")]
        public bool? Enabled { get; set; }

        /// <summary>
        /// The account that's liable for tax. If set, the business address and tax registrations
        /// required to perform the tax calculation are loaded from this account. The tax
        /// transaction is returned in the report of the connected account.
        /// </summary>
        [JsonProperty("liability")]
        public SubscriptionAutomaticTaxLiabilityOptions Liability { get; set; }
    }
}
