// File generated from our OpenAPI spec
namespace Stripe.V2.Core
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Stripe.Infrastructure;
    using STJS = System.Text.Json.Serialization;


    [STJS.JsonConverter(typeof(STJStripeOptionsConverter))]
    public class AccountCreateOptions : BaseOptions, IHasMetadata
    {
        /// <summary>
        /// The account token generated by the account token api.
        /// </summary>
        [JsonProperty("account_token")]
        [STJS.JsonPropertyName("account_token")]
        public string AccountToken { get; set; }

        /// <summary>
        /// An Account Configuration which allows the Account to take on a key persona across Stripe
        /// products.
        /// </summary>
        [JsonProperty("configuration")]
        [STJS.JsonPropertyName("configuration")]
        public AccountCreateConfigurationOptions Configuration { get; set; }

        /// <summary>
        /// The default contact email address for the Account. Required when configuring the account
        /// as a merchant or recipient.
        /// </summary>
        [JsonProperty("contact_email")]
        [STJS.JsonPropertyName("contact_email")]
        public string ContactEmail { get; set; }

        /// <summary>
        /// The default contact phone for the Account.
        /// </summary>
        [JsonProperty("contact_phone")]
        [STJS.JsonPropertyName("contact_phone")]
        public string ContactPhone { get; set; }

        /// <summary>
        /// A value indicating the Stripe dashboard this Account has access to. This will depend on
        /// which configurations are enabled for this account.
        /// One of: <c>express</c>, <c>full</c>, or <c>none</c>.
        /// </summary>
        [JsonProperty("dashboard")]
        [STJS.JsonPropertyName("dashboard")]
        public string Dashboard { get; set; }

        /// <summary>
        /// Default values to be used on Account Configurations.
        /// </summary>
        [JsonProperty("defaults")]
        [STJS.JsonPropertyName("defaults")]
        public AccountCreateDefaultsOptions Defaults { get; set; }

        /// <summary>
        /// A descriptive name for the Account. This name will be surfaced in the Stripe Dashboard
        /// and on any invoices sent to the Account.
        /// </summary>
        [JsonProperty("display_name")]
        [STJS.JsonPropertyName("display_name")]
        public string DisplayName { get; set; }

        /// <summary>
        /// Information about the company, individual, and business represented by the Account.
        /// </summary>
        [JsonProperty("identity")]
        [STJS.JsonPropertyName("identity")]
        public AccountCreateIdentityOptions Identity { get; set; }

        /// <summary>
        /// Additional fields to include in the response.
        /// One of: <c>configuration.card_creator</c>, <c>configuration.customer</c>,
        /// <c>configuration.merchant</c>, <c>configuration.recipient</c>,
        /// <c>configuration.storer</c>, <c>defaults</c>, <c>future_requirements</c>,
        /// <c>identity</c>, or <c>requirements</c>.
        /// </summary>
        [JsonProperty("include")]
        [STJS.JsonPropertyName("include")]
        public List<string> Include { get; set; }

        /// <summary>
        /// Set of key-value pairs that you can attach to an object. This can be useful for storing
        /// additional information about the object in a structured format.
        /// </summary>
        [JsonProperty("metadata")]
        [STJS.JsonPropertyName("metadata")]
        public Dictionary<string, string> Metadata { get; set; }
    }
}
