// File generated from our OpenAPI spec
namespace Stripe.Events
{
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Newtonsoft.Json;
#if NET6_0_OR_GREATER
    using STJS = System.Text.Json.Serialization;
#endif

    public class V2BillingCadenceBilledEventData : StripeEntity<V2BillingCadenceBilledEventData>
    {
        /// <summary>
        /// The IDs of the invoices that were generated by the tick for this Cadence.
        /// </summary>
        [JsonProperty("invoices")]
#if NET6_0_OR_GREATER
        [STJS.JsonPropertyName("invoices")]
#endif
        public List<string> Invoices { get; set; }
    }
}
