// File generated from our OpenAPI spec
namespace Stripe.Events
{
    using System.Collections.Generic;
    using System.Threading.Tasks;
    using Newtonsoft.Json;
    using Stripe.Infrastructure;
    using STJS = System.Text.Json.Serialization;

    public class V2BillingCadenceBilledEventData : StripeEntity<V2BillingCadenceBilledEventData>
    {
        /// <summary>
        /// The IDs of the invoices that were generated by the tick for this Cadence.
        /// </summary>
        [JsonProperty("invoices")]
        [STJS.JsonPropertyName("invoices")]
        public List<string> Invoices { get; set; }
    }
}
