// File generated from our OpenAPI spec
namespace Stripe
{
    using Newtonsoft.Json;
    using Stripe.Infrastructure;
    using STJS = System.Text.Json.Serialization;


    [STJS.JsonConverter(typeof(STJStripeOptionsConverter))]
    public class QuoteInvoiceSettingsOptions : INestedOptions
    {
        /// <summary>
        /// Number of days within which a customer must pay the invoice generated by this quote.
        /// This value will be <c>null</c> for quotes where
        /// <c>collection_method=charge_automatically</c>.
        /// </summary>
        [JsonProperty("days_until_due")]
        [STJS.JsonPropertyName("days_until_due")]
        public long? DaysUntilDue { get; set; }

        /// <summary>
        /// The connected account that issues the invoice. The invoice is presented with the
        /// branding and support information of the specified account.
        /// </summary>
        [JsonProperty("issuer")]
        [STJS.JsonPropertyName("issuer")]
        public QuoteInvoiceSettingsIssuerOptions Issuer { get; set; }
    }
}
