// File generated from our OpenAPI spec
namespace Stripe.V2.MoneyManagement
{
    using Newtonsoft.Json;
    using Stripe.Infrastructure;
    using STJS = System.Text.Json.Serialization;

    [STJS.JsonConverter(typeof(STJStripeOptionsConverter))]
    public class OutboundSetupIntentCreatePayoutMethodDataPixOptions : INestedOptions
    {
        /// <summary>
        /// A static PIX QR code payload generated by the destination bank. Exactly one of pix_key
        /// or br_code must be set.
        /// </summary>
        [JsonProperty("br_code")]
        [STJS.JsonPropertyName("br_code")]
        public string BrCode { get; set; }

        /// <summary>
        /// The PIX key for the destination. May be a phone number, email address, CPF, CNPJ, or
        /// random key. Exactly one of pix_key or br_code must be set.
        /// </summary>
        [JsonProperty("pix_key")]
        [STJS.JsonPropertyName("pix_key")]
        public string PixKey { get; set; }
    }
}
