// File generated from our OpenAPI spec
namespace Stripe
{
    using Newtonsoft.Json;
    using Stripe.Infrastructure;
    using STJS = System.Text.Json.Serialization;

    [STJS.JsonConverter(typeof(STJStripeEntityConverter))]
    public class SetupAttemptPaymentMethodDetailsCardPresent : StripeEntity<SetupAttemptPaymentMethodDetailsCardPresent>
    {
        #region Expandable GeneratedCard

        /// <summary>
        /// (ID of the PaymentMethod)
        /// The ID of the Card PaymentMethod which was generated by this SetupAttempt.
        /// </summary>
        [JsonIgnore]
        [STJS.JsonIgnore]
        public string GeneratedCardId
        {
            get => this.InternalGeneratedCard?.Id;
            set => this.InternalGeneratedCard = SetExpandableFieldId(value, this.InternalGeneratedCard);
        }

        /// <summary>
        /// (Expanded)
        /// The ID of the Card PaymentMethod which was generated by this SetupAttempt.
        ///
        /// For more information, see the <a href="https://stripe.com/docs/expand">expand documentation</a>.
        /// </summary>
        [JsonIgnore]
        [STJS.JsonIgnore]
        public PaymentMethod GeneratedCard
        {
            get => this.InternalGeneratedCard?.ExpandedObject;
            set => this.InternalGeneratedCard = SetExpandableFieldObject(value, this.InternalGeneratedCard);
        }

        [JsonProperty("generated_card")]
        [JsonConverter(typeof(ExpandableFieldConverter<PaymentMethod>))]
        [STJS.JsonPropertyName("generated_card")]
        [STJS.JsonConverter(typeof(STJExpandableFieldConverter<PaymentMethod>))]
        internal ExpandableField<PaymentMethod> InternalGeneratedCard { get; set; }
        #endregion

        /// <summary>
        /// Details about payments collected offline.
        /// </summary>
        [JsonProperty("offline")]
        [STJS.JsonPropertyName("offline")]
        public SetupAttemptPaymentMethodDetailsCardPresentOffline Offline { get; set; }
    }
}
