// File generated from our OpenAPI spec
namespace Stripe
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Stripe.Infrastructure;
    using STJS = System.Text.Json.Serialization;

    [STJS.JsonConverter(typeof(STJStripeOptionsConverter))]
    public class SetupIntentPaymentMethodOptionsPaypalOptions : INestedOptions
    {
        /// <summary>
        /// The PayPal Billing Agreement ID (BAID). This is an ID generated by PayPal which
        /// represents the mandate between the merchant and the customer.
        /// </summary>
        [JsonProperty("billing_agreement_id")]
        [STJS.JsonPropertyName("billing_agreement_id")]
        public string BillingAgreementId { get; set; }

        [JsonProperty("currency")]
#if NET6_0_OR_GREATER
        [STJS.JsonPropertyName("currency")]
#endif
        public string Currency { get; set; }

        /// <summary>
        /// The Stripe connected account IDs of the sellers on the platform for this transaction
        /// (optional). Only allowed when <a
        /// href="https://stripe.com/docs/connect/separate-charges-and-transfers">separate charges
        /// and transfers</a> are used.
        /// </summary>
        [JsonProperty("subsellers")]
#if NET6_0_OR_GREATER
        [STJS.JsonPropertyName("subsellers")]
#endif
        public List<string> Subsellers { get; set; }
    }
}
