// File generated from our OpenAPI spec
namespace Stripe
{
    using Newtonsoft.Json;

    public class ChargePaymentMethodDetailsPaypal : StripeEntity<ChargePaymentMethodDetailsPaypal>
    {
        /// <summary>
        /// Owner's email. Values are provided by PayPal directly (if supported) at the time of
        /// authorization or settlement. They cannot be set or mutated.
        /// </summary>
        [JsonProperty("payer_email")]
        public string PayerEmail { get; set; }

        /// <summary>
        /// PayPal account PayerID. This identifier uniquely identifies the PayPal customer.
        /// </summary>
        [JsonProperty("payer_id")]
        public string PayerId { get; set; }

        /// <summary>
        /// Owner's full name. Values provided by PayPal directly (if supported) at the time of
        /// authorization or settlement. They cannot be set or mutated.
        /// </summary>
        [JsonProperty("payer_name")]
        public string PayerName { get; set; }

        /// <summary>
        /// The level of protection offered as defined by PayPal Seller Protection for Merchants,
        /// for this transaction.
        /// </summary>
        [JsonProperty("seller_protection")]
        public ChargePaymentMethodDetailsPaypalSellerProtection SellerProtection { get; set; }

        /// <summary>
        /// A unique ID generated by PayPal for this transaction.
        /// </summary>
        [JsonProperty("transaction_id")]
        public string TransactionId { get; set; }
    }
}
