// File generated from our OpenAPI spec
namespace Stripe
{
    using Newtonsoft.Json;

    public class ChargePaymentMethodDetailsGrabpay : StripeEntity<ChargePaymentMethodDetailsGrabpay>
    {
        /// <summary>
        /// Unique transaction id generated by GrabPay.
        /// </summary>
        [JsonProperty("transaction_id")]
        public string TransactionId { get; set; }
    }
}
