// File generated from our OpenAPI spec
namespace Stripe
{
    using Newtonsoft.Json;

    public class ChargePaymentMethodDetailsPromptpay : StripeEntity<ChargePaymentMethodDetailsPromptpay>
    {
        /// <summary>
        /// Bill reference generated by PromptPay.
        /// </summary>
        [JsonProperty("reference")]
        public string Reference { get; set; }
    }
}
