// File generated from our OpenAPI spec
namespace Stripe
{
    using Newtonsoft.Json;
#if NET6_0_OR_GREATER
    using STJS = System.Text.Json.Serialization;
#endif

    public class ChargePaymentMethodDetailsGrabpay : StripeEntity<ChargePaymentMethodDetailsGrabpay>
    {
        /// <summary>
        /// Unique transaction id generated by GrabPay.
        /// </summary>
        [JsonProperty("transaction_id")]
#if NET6_0_OR_GREATER
        [STJS.JsonPropertyName("transaction_id")]
#endif

        public string TransactionId { get; set; }
    }
}
