// File generated from our OpenAPI spec
namespace Stripe
{
    using Newtonsoft.Json;
    using Stripe.Infrastructure;
    using STJS = System.Text.Json.Serialization;

    [STJS.JsonConverter(typeof(STJStripeEntityConverter))]
    public class ChargePaymentMethodDetailsPix : StripeEntity<ChargePaymentMethodDetailsPix>
    {
        /// <summary>
        /// Unique transaction id generated by BCB.
        /// </summary>
        [JsonProperty("bank_transaction_id")]
        [STJS.JsonPropertyName("bank_transaction_id")]
        public string BankTransactionId { get; set; }

        /// <summary>
        /// ID of the multi use Mandate generated by the PaymentIntent.
        /// </summary>
        [JsonProperty("mandate")]
#if NET6_0_OR_GREATER
        [STJS.JsonPropertyName("mandate")]
#endif
        public string Mandate { get; set; }
    }
}
