// File generated from our OpenAPI spec
namespace Stripe
{
    using Newtonsoft.Json;
    using Stripe.Infrastructure;
    using STJS = System.Text.Json.Serialization;

    [STJS.JsonConverter(typeof(STJStripeEntityConverter))]
    public class ChargePaymentMethodDetailsPix : StripeEntity<ChargePaymentMethodDetailsPix>
    {
        /// <summary>
        /// Unique transaction id generated by BCB.
        /// </summary>
        [JsonProperty("bank_transaction_id")]
        [STJS.JsonPropertyName("bank_transaction_id")]
        public string BankTransactionId { get; set; }

        /// <summary>
        /// Uniquely identifies this particular Pix account. You can use this attribute to check
        /// whether two Pix accounts are the same.
        /// </summary>
        [JsonProperty("fingerprint")]
        [STJS.JsonPropertyName("fingerprint")]
        public string Fingerprint { get; set; }

        /// <summary>
        /// ID of the multi use Mandate generated by the PaymentIntent.
        /// </summary>
        [JsonProperty("mandate")]
        [STJS.JsonPropertyName("mandate")]
        public string Mandate { get; set; }
    }
}
