// File generated from our OpenAPI spec
namespace Stripe
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Stripe.Infrastructure;
    using STJS = System.Text.Json.Serialization;

    [STJS.JsonConverter(typeof(STJStripeOptionsConverter))]
    public class SubscriptionSchedulePhaseInvoiceSettingsOptions : INestedOptions, IHasSetTracking
    {
        private List<string> accountTaxIds;
        private List<SubscriptionSchedulePhaseInvoiceSettingsCustomFieldOptions> customFields;
        private string description;
        private string footer;

        [JsonIgnore]
        [STJS.JsonIgnore]
        internal SetTracker SetTracker { get; } = new SetTracker();

        /// <summary>
        /// The account tax IDs associated with this phase of the subscription schedule. Will be set
        /// on invoices generated by this phase of the subscription schedule.
        /// </summary>
        [JsonProperty("account_tax_ids", NullValueHandling = NullValueHandling.Ignore)]
        [STJS.JsonPropertyName("account_tax_ids")]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingNull)]
        public List<string> AccountTaxIds
        {
            get => this.accountTaxIds;
            set
            {
                this.accountTaxIds = value;
                this.SetTracker.Track();
            }
        }

        /// <summary>
        /// A list of up to 4 custom fields to be displayed on the invoice.
        /// </summary>
        [JsonProperty("custom_fields", NullValueHandling = NullValueHandling.Ignore)]
        [STJS.JsonPropertyName("custom_fields")]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingNull)]
        public List<SubscriptionSchedulePhaseInvoiceSettingsCustomFieldOptions> CustomFields
        {
            get => this.customFields;
            set
            {
                this.customFields = value;
                this.SetTracker.Track();
            }
        }

        /// <summary>
        /// Number of days within which a customer must pay invoices generated by this subscription
        /// schedule. This value will be <c>null</c> for subscription schedules where
        /// <c>collection_method=charge_automatically</c>.
        /// </summary>
        [JsonProperty("days_until_due")]
        [STJS.JsonPropertyName("days_until_due")]
        public long? DaysUntilDue { get; set; }

        /// <summary>
        /// An arbitrary string attached to the object. Often useful for displaying to users.
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore)]
        [STJS.JsonPropertyName("description")]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingNull)]
        public string Description
        {
            get => this.description;
            set
            {
                this.description = value;
                this.SetTracker.Track();
            }
        }

        /// <summary>
        /// Footer to be displayed on the invoice.
        /// </summary>
        [JsonProperty("footer", NullValueHandling = NullValueHandling.Ignore)]
        [STJS.JsonPropertyName("footer")]
        [STJS.JsonIgnore(Condition = STJS.JsonIgnoreCondition.WhenWritingNull)]
        public string Footer
        {
            get => this.footer;
            set
            {
                this.footer = value;
                this.SetTracker.Track();
            }
        }

        /// <summary>
        /// The connected account that issues the invoice. The invoice is presented with the
        /// branding and support information of the specified account.
        /// </summary>
        [JsonProperty("issuer")]
        [STJS.JsonPropertyName("issuer")]
        public SubscriptionSchedulePhaseInvoiceSettingsIssuerOptions Issuer { get; set; }

        bool IHasSetTracking.IsPropertySet(string propertyName)
        {
            return this.SetTracker.IsSet(propertyName);
        }
    }
}
