// File generated from our OpenAPI spec
namespace Stripe
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public class SubscriptionScheduleDefaultSettingsInvoiceSettingsOptions : INestedOptions
    {
        /// <summary>
        /// The account tax IDs associated with the subscription schedule. Will be set on invoices
        /// generated by the subscription schedule.
        /// </summary>
        [JsonProperty("account_tax_ids")]
        public List<string> AccountTaxIds { get; set; }

        /// <summary>
        /// Number of days within which a customer must pay invoices generated by this subscription
        /// schedule. This value will be <c>null</c> for subscription schedules where
        /// <c>collection_method=charge_automatically</c>.
        /// </summary>
        [JsonProperty("days_until_due")]
        public long? DaysUntilDue { get; set; }

        /// <summary>
        /// The connected account that issues the invoice. The invoice is presented with the
        /// branding and support information of the specified account.
        /// </summary>
        [JsonProperty("issuer")]
        public SubscriptionScheduleDefaultSettingsInvoiceSettingsIssuerOptions Issuer { get; set; }
    }
}
