namespace Stripe
{
    using Newtonsoft.Json;

    public class SubscriptionSchedulePhaseInvoiceSettingsOptions : INestedOptions
    {
        /// <summary>
        /// Number of days within which a customer must pay invoices generated by this subscription
        /// schedule. This value will be <c>null</c> for subscription schedules where
        /// <c>billing=charge_automatically</c>.
        /// </summary>
        [JsonProperty("days_until_due")]
        public long? DaysUntilDue { get; set; }
    }
}
