// File generated from our OpenAPI spec
namespace Stripe
{
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Stripe.Infrastructure;
    using STJS = System.Text.Json.Serialization;


    [STJS.JsonConverter(typeof(STJStripeOptionsConverter))]
    public class SubscriptionScheduleDefaultSettingsInvoiceSettingsOptions : INestedOptions, IHasSetTracking
    {
        private List<string> accountTaxIds;

        [JsonIgnore]
        [STJS.JsonIgnore]
        internal SetTracker SetTracker { get; } = new SetTracker();

        /// <summary>
        /// The account tax IDs associated with the subscription schedule. Will be set on invoices
        /// generated by the subscription schedule.
        /// </summary>
        [JsonProperty("account_tax_ids")]
        [STJS.JsonPropertyName("account_tax_ids")]
        public List<string> AccountTaxIds
        {
            get => this.accountTaxIds;
            set
            {
                this.accountTaxIds = value;
                this.SetTracker.Track();
            }
        }

        /// <summary>
        /// Number of days within which a customer must pay invoices generated by this subscription
        /// schedule. This value will be <c>null</c> for subscription schedules where
        /// <c>collection_method=charge_automatically</c>.
        /// </summary>
        [JsonProperty("days_until_due")]
        [STJS.JsonPropertyName("days_until_due")]
        public long? DaysUntilDue { get; set; }

        /// <summary>
        /// The connected account that issues the invoice. The invoice is presented with the
        /// branding and support information of the specified account.
        /// </summary>
        [JsonProperty("issuer")]
        [STJS.JsonPropertyName("issuer")]
        public SubscriptionScheduleDefaultSettingsInvoiceSettingsIssuerOptions Issuer { get; set; }

        bool IHasSetTracking.IsPropertySet(string propertyName)
        {
            return this.SetTracker.IsSet(propertyName);
        }
    }
}
