// File generated from our OpenAPI spec
namespace Stripe.Capital
{
    using System.Collections.Generic;
    using System.Linq;
    using Newtonsoft.Json;
    using Stripe.Infrastructure;
    using STJS = System.Text.Json.Serialization;

    [STJS.JsonConverter(typeof(STJStripeEntityConverter))]
    public class FinancingOfferFinancingDocuments : StripeEntity<FinancingOfferFinancingDocuments>
    {
        #region Expandable FinancingAgreement

        /// <summary>
        /// (ID of the File)
        /// The primary contract that defines the financing provided to the connected account,
        /// including the funded amount, repayment terms, fees, and each party’s obligations. Only
        /// available once the financing offer has been paid out.
        /// </summary>
        [JsonIgnore]
        [STJS.JsonIgnore]
        public string FinancingAgreementId
        {
            get => this.InternalFinancingAgreement?.Id;
            set => this.InternalFinancingAgreement = SetExpandableFieldId(value, this.InternalFinancingAgreement);
        }

        /// <summary>
        /// (Expanded)
        /// The primary contract that defines the financing provided to the connected account,
        /// including the funded amount, repayment terms, fees, and each party’s obligations. Only
        /// available once the financing offer has been paid out.
        ///
        /// For more information, see the <a href="https://stripe.com/docs/expand">expand documentation</a>.
        /// </summary>
        [JsonIgnore]
        [STJS.JsonIgnore]
        public File FinancingAgreement
        {
            get => this.InternalFinancingAgreement?.ExpandedObject;
            set => this.InternalFinancingAgreement = SetExpandableFieldObject(value, this.InternalFinancingAgreement);
        }

        [JsonProperty("financing_agreement")]
        [JsonConverter(typeof(ExpandableFieldConverter<File>))]
        [STJS.JsonPropertyName("financing_agreement")]
        [STJS.JsonConverter(typeof(STJExpandableFieldConverter<File>))]
        internal ExpandableField<File> InternalFinancingAgreement { get; set; }
        #endregion

        #region Expandable StateSalesBasedFinancingAgreement

        /// <summary>
        /// (ID of the File)
        /// A state-specific disclosure required by certain US states for sales-based financing. It
        /// supplements the main financing agreement and may be generated by Stripe or supplied by a
        /// financing partner, depending on the product.
        /// </summary>
        [JsonIgnore]
        [STJS.JsonIgnore]
        public string StateSalesBasedFinancingAgreementId
        {
            get => this.InternalStateSalesBasedFinancingAgreement?.Id;
            set => this.InternalStateSalesBasedFinancingAgreement = SetExpandableFieldId(value, this.InternalStateSalesBasedFinancingAgreement);
        }

        /// <summary>
        /// (Expanded)
        /// A state-specific disclosure required by certain US states for sales-based financing. It
        /// supplements the main financing agreement and may be generated by Stripe or supplied by a
        /// financing partner, depending on the product.
        ///
        /// For more information, see the <a href="https://stripe.com/docs/expand">expand documentation</a>.
        /// </summary>
        [JsonIgnore]
        [STJS.JsonIgnore]
        public File StateSalesBasedFinancingAgreement
        {
            get => this.InternalStateSalesBasedFinancingAgreement?.ExpandedObject;
            set => this.InternalStateSalesBasedFinancingAgreement = SetExpandableFieldObject(value, this.InternalStateSalesBasedFinancingAgreement);
        }

        [JsonProperty("state_sales_based_financing_agreement")]
        [JsonConverter(typeof(ExpandableFieldConverter<File>))]
        [STJS.JsonPropertyName("state_sales_based_financing_agreement")]
        [STJS.JsonConverter(typeof(STJExpandableFieldConverter<File>))]
        internal ExpandableField<File> InternalStateSalesBasedFinancingAgreement { get; set; }
        #endregion

        #region Expandable TransferAgreements

        /// <summary>
        /// (IDs of the TransferAgreements)
        /// A partner-provided contract documenting the transfer or assignment of rights associated
        /// with the financing. It is separate from the main financing agreement, and a single
        /// financing may have multiple transfer agreements.
        /// </summary>
        [JsonIgnore]
        [STJS.JsonIgnore]
        public List<string> TransferAgreementIds
        {
            get => this.InternalTransferAgreements?.Select((x) => x.Id).ToList();
            set => this.InternalTransferAgreements = SetExpandableArrayIds<File>(value);
        }

        /// <summary>
        /// (Expanded)
        /// A partner-provided contract documenting the transfer or assignment of rights associated
        /// with the financing. It is separate from the main financing agreement, and a single
        /// financing may have multiple transfer agreements.
        ///
        /// For more information, see the <a href="https://stripe.com/docs/expand">expand documentation</a>.
        /// </summary>
        [JsonIgnore]
        [STJS.JsonIgnore]
        public List<File> TransferAgreements
        {
            get => this.InternalTransferAgreements?.Select((x) => x.ExpandedObject).ToList();
            set => this.InternalTransferAgreements = SetExpandableArrayObjects(value);
        }

        [JsonProperty("transfer_agreements", ItemConverterType = typeof(ExpandableFieldConverter<File>))]
        [STJS.JsonPropertyName("transfer_agreements")]
        internal List<ExpandableField<File>> InternalTransferAgreements { get; set; }
        #endregion
    }
}
