// File generated from our OpenAPI spec
namespace Stripe
{
    using Newtonsoft.Json;
#if NET6_0_OR_GREATER
    using STJS = System.Text.Json.Serialization;
#endif

    public class MandatePaymentMethodDetailsPaypal : StripeEntity<MandatePaymentMethodDetailsPaypal>
    {
        /// <summary>
        /// The PayPal Billing Agreement ID (BAID). This is an ID generated by PayPal which
        /// represents the mandate between the merchant and the customer.
        /// </summary>
        [JsonProperty("billing_agreement_id")]
#if NET6_0_OR_GREATER
        [STJS.JsonPropertyName("billing_agreement_id")]
#endif
        public string BillingAgreementId { get; set; }

        /// <summary>
        /// PayPal account PayerID. This identifier uniquely identifies the PayPal customer.
        /// </summary>
        [JsonProperty("payer_id")]
#if NET6_0_OR_GREATER
        [STJS.JsonPropertyName("payer_id")]
#endif
        public string PayerId { get; set; }
    }
}
