name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
      - beta
      - sdk-release/**
      - feature/**
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
    branches:
      - master
      - beta
      - private-preview
      - sdk-release/**
      - feature/**

permissions: {}

jobs:
  prepare-dotnet-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      latest-dotnet-version: ${{ steps.latest-dotnet-version.outputs.latest_dotnet_version }}
      test-matrix: ${{ steps.test-matrix.outputs.test_matrix }}
    steps:
      - uses: extractions/setup-just@v2
      - uses: actions/checkout@v6
      - name: Get latest .NET version
        id: latest-dotnet-version
        run: |
          latest_dotnet_version=`just print_latest_supported_dotnet_version`
          echo "latest_dotnet_version=$latest_dotnet_version" >> $GITHUB_OUTPUT
      - name: Get test framework matrix
        id: test-matrix
        run: |
          test_matrix=`just print_test_matrix_json`
          echo "test_matrix=$test_matrix" >> $GITHUB_OUTPUT

  fetch-openapi:
    name: Fetch OpenAPI spec
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Determine OpenAPI versions and download specs
        run: |
          set -e -o pipefail

          CURL_OPTS=(--retry 3 \
            --retry-all-errors \
            --fail \
            --verbose \
            --no-progress-meter \
            --show-error)

          LATEST_OPENAPI_VERSION=$(curl https://api.github.com/repos/stripe/openapi/releases/latest -s | jq .name -r)
          CURRENT_OPENAPI_VERSION=$(cat OPENAPI_VERSION)
          if [[ "$PR_BODY" == *"TEST USING LATEST OPENAPI"* ]]; then
            OPENAPI_VERSION=$LATEST_OPENAPI_VERSION
          else
            OPENAPI_VERSION=$CURRENT_OPENAPI_VERSION
          fi

          SPEC_NAME="spec3.sdk.yaml"
          FIXTURES_NAME="fixtures3.json"
          if [[ "$GITHUB_BASE" == *"b"* ]]; then
            SPEC_NAME="spec3.beta.sdk.yaml"
            FIXTURES_NAME="fixtures3.beta.json"
          fi
          curl "${CURL_OPTS[@]}" https://raw.githubusercontent.com/stripe/openapi/$OPENAPI_VERSION/openapi/${SPEC_NAME%.yaml}.json -o latest.json
          curl "${CURL_OPTS[@]}" https://raw.githubusercontent.com/stripe/openapi/$OPENAPI_VERSION/openapi/$FIXTURES_NAME -o fixtures.json

        env:
          PR_BODY: ${{ github.event.pull_request.body }}
          GITHUB_BASE: ${{ github.base_ref || github.ref_name }}

      - name: Upload OpenAPI spec
        uses: actions/upload-artifact@v4
        with:
          name: openapi-spec
          path: |
            latest.json
            fixtures.json

  test:
    name: Test (${{ matrix.framework }})
    needs: [prepare-dotnet-versions, fetch-openapi]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        framework: ${{ fromJson(needs.prepare-dotnet-versions.outputs.test-matrix) }}
        exclude:
          - framework: net462
    steps:
      - uses: extractions/setup-just@v2
      - uses: actions/checkout@v6

      - name: Setup .NET (latest SDK)
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "${{ needs.prepare-dotnet-versions.outputs.latest-dotnet-version }}.x"

      - name: Install target framework runtime
        run: |
          channel="${{ matrix.framework }}"
          channel="${channel#net}"
          if [ "$channel" != "${{ needs.prepare-dotnet-versions.outputs.latest-dotnet-version }}" ]; then
            ./scripts/dotnet-install.sh --runtime dotnet --channel "$channel" --install-dir "$DOTNET_ROOT"
          fi

      - name: Install tools
        run: dotnet tool restore

      - name: Build
        run: |
          echo "Building ${{ matrix.framework }} using dotnet v$(dotnet --version)"
          dotnet build src/StripeTests/StripeTests.csproj -c Release -f ${{ matrix.framework }} /p:ContinuousIntegrationBuild=true

      - name: Download OpenAPI spec
        uses: actions/download-artifact@v4
        with:
          name: openapi-spec

      - uses: stripe/openapi/actions/stripe-mock@master
        with:
          base: ${{ github.base_ref || github.ref_name }}
          fixtures: "/workspace/fixtures.json"
          spec_path: "/workspace/latest.json"

      - name: Run tests
        run: dotnet test --no-build -f ${{ matrix.framework }} src/StripeTests/StripeTests.csproj -c Release

  test-net462:
    name: Test (net462)
    needs: [prepare-dotnet-versions, fetch-openapi]
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: extractions/setup-just@v2
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "${{ needs.prepare-dotnet-versions.outputs.latest-dotnet-version }}.x"

      - name: Install tools
        run: dotnet tool restore

      - name: Build
        run: |
          echo "Building net462 using dotnet v$(dotnet --version)"
          dotnet build src/StripeTests/StripeTests.csproj -c Release -f net462 /p:ContinuousIntegrationBuild=true

      - name: Download OpenAPI spec
        uses: actions/download-artifact@v4
        with:
          name: openapi-spec

      - uses: stripe/openapi/actions/stripe-mock@master
        with:
          base: ${{ github.base_ref || github.ref_name }}
          fixtures: "/workspace/fixtures.json"
          spec_path: "/workspace/latest.json"

      - name: Run tests
        run: dotnet test --no-build --configuration Release --framework net462 src/StripeTests/StripeTests.csproj

  pack:
    name: Pack NuGet
    needs: prepare-dotnet-versions
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: extractions/setup-just@v2
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "${{ needs.prepare-dotnet-versions.outputs.latest-dotnet-version }}.x"

      - name: Install tools
        run: dotnet tool restore

      - name: Build Release
        run: dotnet build src/Stripe.net -c Release /p:ContinuousIntegrationBuild=true

      - name: Pack
        run: dotnet pack src/Stripe.net -c Release --no-build --output nuget

      - name: Upload NuGet artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget
          path: nuget/

  build-examples:
    name: Build examples
    needs: prepare-dotnet-versions
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "${{ needs.prepare-dotnet-versions.outputs.latest-dotnet-version }}.x"

      - name: Build examples
        run: dotnet build src/Examples/Examples.sln -c Release

  compat:
    name: Compat
    if: github.event_name == 'pull_request'
    needs: prepare-dotnet-versions
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ needs.prepare-dotnet-versions.outputs.latest-dotnet-version }}
      - name: Run backcompat check
        run: dotnet pack src/Stripe.net -p:RunBaselineCheck=true

  publish:
    name: Publish
    if: (((github.event_name == 'push') || (github.event_name == 'workflow_dispatch')) && startsWith(github.ref, 'refs/tags/v'))
    needs: [test, test-net462, pack, prepare-dotnet-versions]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          name: nuget
          path: nuget
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ needs.prepare-dotnet-versions.outputs.latest-dotnet-version }}
      - name: Publish NuGet packages to NuGet
        run: dotnet nuget push nuget/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source "nuget.org" --timeout 1200
      - uses: stripe/openapi/actions/notify-release@master
        if: always()
        with:
          bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
