name: CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
      - beta
      - private-preview
      - sdk-release/**
      - feature/**
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:
    branches:
      - master
      - beta
      - private-preview
      - sdk-release/**
      - feature/**

permissions: {}

jobs:
  prepare-dotnet-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      latest-dotnet-version: ${{ steps.latest-dotnet-version.outputs.latest_dotnet_version }}
      test-matrix: ${{ steps.test-matrix.outputs.test_matrix }}
    steps:
      - uses: extractions/setup-just@v2
      - uses: actions/checkout@v6
      - name: Get latest .NET version
        id: latest-dotnet-version
        run: |
          latest_dotnet_version=`just print_latest_supported_dotnet_version`
          echo "latest_dotnet_version=$latest_dotnet_version" >> $GITHUB_OUTPUT
      - name: Get test framework matrix
        id: test-matrix
        run: |
          test_matrix=`just print_test_matrix_json`
          echo "test_matrix=$test_matrix" >> $GITHUB_OUTPUT

  test:
    name: Test (${{ matrix.framework }}, ubuntu)
    needs: [prepare-dotnet-versions]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        framework: ${{ fromJson(needs.prepare-dotnet-versions.outputs.test-matrix) }}
        exclude:
          - framework: net462
    steps:
      - uses: extractions/setup-just@v2
      - uses: actions/checkout@v6

      - name: Setup .NET (latest SDK)
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "${{ needs.prepare-dotnet-versions.outputs.latest-dotnet-version }}.x"

      - name: Install target framework runtime
        run: |
          channel="${{ matrix.framework }}"
          channel="${channel#net}"
          if [ "$channel" != "${{ needs.prepare-dotnet-versions.outputs.latest-dotnet-version }}" ]; then
            ./scripts/dotnet-install.sh --runtime dotnet --channel "$channel" --install-dir "$DOTNET_ROOT"
          fi

      - name: Install tools
        run: dotnet tool restore

      - name: Build
        run: |
          echo "Building ${{ matrix.framework }} using dotnet v$(dotnet --version)"
          dotnet build src/StripeTests/StripeTests.csproj -c Release -f ${{ matrix.framework }} /p:ContinuousIntegrationBuild=true

      - uses: stripe/openapi/actions/stripe-mock@master

      - name: Run tests
        run: dotnet test --no-build -f ${{ matrix.framework }} src/StripeTests/StripeTests.csproj -c Release

  test-net462:
    name: Test (net462, windows)
    needs: [prepare-dotnet-versions]
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: extractions/setup-just@v2
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "${{ needs.prepare-dotnet-versions.outputs.latest-dotnet-version }}.x"

      - name: Install tools
        run: dotnet tool restore

      - name: Build
        run: |
          echo "Building net462 using dotnet v$(dotnet --version)"
          dotnet build src/StripeTests/StripeTests.csproj -c Release -f net462 /p:ContinuousIntegrationBuild=true

      - uses: stripe/openapi/actions/stripe-mock@master

      - name: Run tests
        run: dotnet test --no-build --configuration Release --framework net462 src/StripeTests/StripeTests.csproj

  build:
    name: Build
    needs: [test, test-net462, prepare-dotnet-versions]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: extractions/setup-just@v2
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "${{ needs.prepare-dotnet-versions.outputs.latest-dotnet-version }}.x"

      - name: Install tools
        run: dotnet tool restore

      - name: Build Release
        run: dotnet build src/Stripe.net -c Release /p:ContinuousIntegrationBuild=true

  pack:
    name: Pack NuGet
    if: (((github.event_name == 'push') || (github.event_name == 'workflow_dispatch')) && startsWith(github.ref, 'refs/tags/v'))
    needs: [build, prepare-dotnet-versions]
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: extractions/setup-just@v2
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "${{ needs.prepare-dotnet-versions.outputs.latest-dotnet-version }}.x"

      - name: Install tools
        run: dotnet tool restore

      - name: Build Release
        run: dotnet build src/Stripe.net -c Release /p:ContinuousIntegrationBuild=true

      - name: Pack
        run: dotnet pack src/Stripe.net -c Release --no-build --output nuget

      - name: Upload NuGet artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget
          path: nuget/

  build-examples:
    name: Build examples
    needs: prepare-dotnet-versions
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "${{ needs.prepare-dotnet-versions.outputs.latest-dotnet-version }}.x"

      - name: Build examples
        run: dotnet build src/Examples/Examples.sln -c Release

  compat:
    name: Compat
    if: github.event_name == 'pull_request'
    needs: prepare-dotnet-versions
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ needs.prepare-dotnet-versions.outputs.latest-dotnet-version }}
      - name: Run backcompat check
        run: dotnet pack src/Stripe.net -p:RunBaselineCheck=true

  publish:
    name: Publish
    if: (((github.event_name == 'push') || (github.event_name == 'workflow_dispatch')) && startsWith(github.ref, 'refs/tags/v'))
    needs: [pack, prepare-dotnet-versions]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          name: nuget
          path: nuget
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ needs.prepare-dotnet-versions.outputs.latest-dotnet-version }}
      - name: Publish NuGet packages to NuGet
        run: dotnet nuget push nuget/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source "nuget.org" --timeout 1200
      - uses: stripe/openapi/actions/notify-release@master
        if: always()
        with:
          bot_token: ${{ secrets.SLACK_BOT_TOKEN }}
