// File generated from our OpenAPI spec
namespace Stripe.V2.MoneyManagement
{
    using Newtonsoft.Json;
    using Stripe.Infrastructure;
    using STJS = System.Text.Json.Serialization;

    [STJS.JsonConverter(typeof(STJStripeEntityConverter))]
    public class PayoutMethodPix : StripeEntity<PayoutMethodPix>
    {
        /// <summary>
        /// A static PIX QR code payload generated by the destination bank. Exactly one of pix_key
        /// or br_code must be set.
        /// </summary>
        [JsonProperty("br_code")]
        [STJS.JsonPropertyName("br_code")]
        public string BrCode { get; set; }

        /// <summary>
        /// The PIX key for the destination. May be a phone number, email address, CPF, CNPJ, or
        /// random key. Exactly one of pix_key or br_code must be set. Annotated as TAX_ID_SECRET
        /// because a PIX key can be a CPF or CNPJ (Brazilian tax IDs), which are classified as
        /// sensitive under LGPD and consistent with how CPF/CNPJ are annotated elsewhere in the
        /// codebase.
        /// </summary>
        [JsonProperty("pix_key")]
        [STJS.JsonPropertyName("pix_key")]
        public string PixKey { get; set; }
    }
}
